"use client";
import { Nunito } from "next/font/google";
import "@/styles/globals.css";
import Script from "next/script";
import { Providers } from "./providers";

const nunito = Nunito({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script src="https://saturn.tech/widget.js"></Script>
      <body className={nunito.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
